"""Provider-neutral memory abstractions and implementations."""

from .episodic import (
    EmbeddingDigestRecall,
    EventScope,
    EpisodicCurationRequest,
    EpisodicCurationResult,
    EpisodicConcurrencyError,
    EpisodicDigest,
    EpisodicEvent,
    EpisodicMemory,
    EpisodicMemoryManager,
    EpisodicMemoryRequest,
    EpisodicMemoryResult,
    EpisodicSession,
    EpisodicSessionQuery,
    EpisodicCompatibilityError,
    JsonlEpisodicMemory,
    SqliteEpisodicMemory,
)
from .curation import (
    CurationConflictError,
    CurationError,
    CurationResult,
    CurationService,
    CurationSessionNotFoundError,
    CurationStorageError,
    DigestGenerationError,
    DigestGenerationRequest,
    DigestGenerator,
    DigestPublicationError,
)
from .digest_generation import GaletDigestGenerator, GaletDigestPolicy
from .working import (WorkingMemory, WorkingMemoryConflict, WorkingRunUnavailable,
                      WorkingValue, SqliteWorkingMemory)
from .procedural import (
    ContextProceduralMemory,
    FileContextRepository,
    FileProceduralMemory,
    ProceduralLayout,
    ProceduralMemory,
    ProceduralMemoryRequest,
    ProceduralMemoryResult,
    ProceduralSkill,
)
from .semantic import (
    SemanticDocument,
    SemanticMemory,
    SemanticMemoryRequest,
    SemanticMemoryResult,
    VectorSemanticMemory,
    SemanticIngestionResult,
    SemanticIngestionService,
)
from .ports import (
    CachingEmbeddingProvider,
    EmbeddingCache,
    EmbeddingCacheInfo,
    EmbeddingCacheKey,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "CachingEmbeddingProvider",
    "ContextProceduralMemory",
    "FileContextRepository",
    "FileProceduralMemory",
    "ProceduralLayout",
    "CurationConflictError",
    "CurationError",
    "CurationResult",
    "CurationService",
    "CurationSessionNotFoundError",
    "CurationStorageError",
    "DigestGenerationError",
    "DigestGenerationRequest",
    "DigestGenerator",
    "DigestPublicationError",
    "GaletDigestGenerator",
    "GaletDigestPolicy",
    "WorkingMemory",
    "WorkingMemoryConflict",
    "WorkingRunUnavailable",
    "WorkingValue",
    "SqliteWorkingMemory",
    "EmbeddingDigestRecall",
    "EmbeddingCache",
    "EmbeddingCacheInfo",
    "EmbeddingCacheKey",
    "EventScope",
    "EpisodicCurationRequest",
    "EpisodicCurationResult",
    "EpisodicConcurrencyError",
    "EpisodicDigest",
    "EpisodicEvent",
    "EpisodicMemory",
    "EpisodicMemoryManager",
    "EpisodicMemoryRequest",
    "EpisodicMemoryResult",
    "EpisodicSession",
    "EpisodicSessionQuery",
    "EpisodicCompatibilityError",
    "JsonlEpisodicMemory",
    "SqliteEpisodicMemory",
    "ProceduralMemory",
    "ProceduralMemoryRequest",
    "ProceduralMemoryResult",
    "ProceduralSkill",
    "SemanticDocument",
    "SemanticMemory",
    "SemanticMemoryRequest",
    "SemanticMemoryResult",
    "VectorSemanticMemory",
    "SemanticIngestionResult",
    "SemanticIngestionService",
    "__version__",
]
